// Generated by CoffeeScript 1.6.3
(function() {
  var fixURLs;

  fixURLs = function() {
    var englishURLs, spanishURLs;
    englishURLs = ['index', 'about', 'how-casa-caridad-works', 'Recipient-stories', 'donate'];
    spanishURLs = ['index-es', 'intro', 'como-lo-hacemos', 'vidas-de-nuestros-recipientes', 'donaciones'];
    return $('.language a').click(function() {
      var i, j, proposition, _i, _j, _len, _len1;
      if ($(this).index() === 0) {
        for (_i = 0, _len = spanishURLs.length; _i < _len; _i++) {
          i = spanishURLs[_i];
          proposition = document.URL.indexOf(i) > 0;
          if (proposition === true) {
            window.location = "http://localhost/casa/" + englishURLs[_i] + ".php";
          }
        }
      } else {
        for (_j = 0, _len1 = englishURLs.length; _j < _len1; _j++) {
          j = englishURLs[_j];
          proposition = document.URL.indexOf(j) > 0;
          if (proposition === true) {
            window.location = "http://localhost/casa/" + spanishURLs[_j] + ".php";
          }
        }
      }
      return false;
    });
  };

  fixURLs();

}).call(this);
